<a href="https://colab.research.google.com/github/CarolineGuothesweetie/Lecture-notes/blob/main/Midterm_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
x = [1,2,3,4,5]

y = [7,8,9]
x.insert(5,y)
x

[1, 2, 3, 4, 5, [7, 8, 9]]

In [56]:
x = [1,2,4,5,6,7]
x.insert(2,3)
x

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
x = list(range(10))
x.clear()
x

[]

In [ ]:
x = list(range(2,10,2))
x

[2, 4, 6, 8]

In [65]:
x = list(range(12))
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [ ]:
x = list(range(6))
x[:3]


[0, 1, 2]

In [68]:
x = [1,2,3]

y = [4,5,6]
y + x

[4, 5, 6, 1, 2, 3]

In [71]:
d = {'a':1, 'b':"string", 'c':False}

d['c'] * 3


0

In [ ]:
d = {'a':1, 'b':"string", 'c':False}

d['b'] * 3

'stringstringstring'

In [ ]:
d = {'a':1, 'b':"string", 'c':False}

d.get('b', -4)

'string'

In [ ]:
d = {'a':1, 'b':"string", 'c':False}

d.get('d', -4)

-4

In [ ]:
import numpy as np
x = np.random.rand(5,3)
x

array([[0.22868426, 0.10713382, 0.47110605],
       [0.35842072, 0.84828196, 0.51286248],
       [0.54308256, 0.15768313, 0.17246445],
       [0.6306791 , 0.31253714, 0.73194154],
       [0.43792665, 0.30488717, 0.15372027]])

In [ ]:
import numpy as np

x = np.arange(10)
x.shape

(10,)

In [ ]:
import numpy as np
x = np.arange(10) /3
x

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [ ]:
import numpy as np

x = np.arange(10) >=6
x

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
import numpy as np

x = np.arange(10)
np.logical_and(x>4,x<6)

array([False, False, False, False, False,  True, False, False, False,
       False])

In [58]:
import numpy as np

x = np.random.rand(3,5)

x.sum(axis=1)

array([1.39273145, 3.44722519, 3.13244861])

In [64]:
x = list(range(12))
x.index(2)

2

In [ ]:
x = [1,2,3,4,5,3,2,4,1]
x[0:5]

[1, 2, 3, 4, 5]

In [ ]:
x = [1,2,3,4,5,3,2,4,1]
list(set(x))

[1, 2, 3, 4, 5]