<a href="https://colab.research.google.com/github/CarolineGuothesweetie/Lecture-notes/blob/main/%E2%80%9C01_IntroToNumpy_Lecture_ipynb%E2%80%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Session 05
07/20

## Notes
- Solutions for labs are in their respective session folders (Sessions 2 and 4)
- Solution for Assignment 1 was under Session 04, but moved to a new directory called **Assignment Solutions** to make it easy to see!
- Assignment 02 due TODAY 11pm ET, accepted until Jul 21 11am ET with late penalty. Not accepted after as the solution will be released when the late acceptance deadline is passed. 
- Midterm: during class time, on Qtools, 90 minutes, single submission, open notes but not open collaboration. 
- I see about 20\% of the class did not attempt Lab2 on Qtools - I re-opened it so please use it to practice qtools!
- DataCamp: 12 people (together in both sections) are still MIA - completion rate of any course is ~10\%


## Outline
- Questions about Assignment 2
- Numpy Quiz
- Numpy Lecture
- Numpy Lab

If time permits:
- Object Oriented Programming and Classes

# About

![numpy](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1200px-NumPy_logo_2020.svg.png)


In this notebook we will run through an introduction to [numpy](https://numpy.org/), or numerical python, which is the foundation for the core data analytics and data science ecosystem.

See the absolute beginners intro at the numpy project library:
https://numpy.org/doc/stable/user/absolute_beginners.html




In [1]:
# import the library to get started
import numpy as np

Numpy is the workhorse underneath a number of our tools that we will be using.  At the core, numpy **arrays** look a lot like `lists` that we worked through last week, except that they have additional properties:

1.  numpy arrays can be multi-dimensional 

2.  numpy arrays allow us to do calculations on each element  at the same time (we can't do this with lists).  This is **element wise** calculations.

3.  unlike lists, numpy arrays hold a single **type**

>  ***From above, you see that I imported numpy as np.  This is the standard convention.***

# Lists to numpy arrays

In [2]:
# create a normal list
my_list = [1,2,4,5,6,7]

## print out the type and the values
print(type(my_list))
print(my_list)

<class 'list'>
[1, 2, 4, 5, 6, 7]


In [3]:
# create a new list and perform some math on it
new_list = [1,2,3]
new_list

[1, 2, 3]

In [4]:
# multiple the list by 3 #把list复制三遍
new_list * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [5]:
"ba765"*3

'ba765ba765ba765'

Above shows that just like with `+`, we can repeat the list with `*`. 

While, when we do work with numerical data, we often want to do element-wise math:

In [6]:
# numpy to the rescue
np_arr = np.array(new_list)
np_arr

array([1, 2, 3])

In [7]:
type(np_arr)

numpy.ndarray

In [8]:
# we converted our list to an numpy array. now lets try it
np_arr * 3

array([3, 6, 9])

While lists and tuples are powerful in base python, and we will use them later in the course, when it really comes to analyzing data, the foundations of the tools that we will use are in **numpy**.

Simply, the higher level tools use numpy under the hood, but it's important for us to have a baseline understanding of numpy before we dive into **pandas** a popular library to work with data.

# Numpy Arrays - Single Type Only

Because numpy arrays are built to do calculations, helping us with analyzing data, each array must be of a single type. 

In [9]:
# create a normal list
normal_list = [1, 'a', True]
normal_list

[1, 'a', True]

This does what we expected, it printed a list, and if we wanted, we could even have a list within a list, as we learned last week.

In [10]:
# convert the list to numpy, as we saw above with np.array(<list>)
np_convert = np.array(normal_list)
np_convert

array(['1', 'a', 'True'], dtype='<U21')

In [11]:
np_convert.shape

(3,)

In [12]:
type(np_convert)

numpy.ndarray




Look at what we have above.  Numpy needs to have all elements in an array be of the same type.  But it didn't error out, nor it did exclude some elements. What did numpy do?

# Core numpy features

## nd arrays

Multidimensional arrays and lists of lists are conceptually similar:

In [37]:
# 3-dimension array example as following:
ex_arr = np.array([[[1,1,4],[2,2,5],[3,3,6]], [[1,1,4],[2,2,5],[3,3,6]]])
ex_arr

array([[[1, 1, 4],
        [2, 2, 5],
        [3, 3, 6]],

       [[1, 1, 4],
        [2, 2, 5],
        [3, 3, 6]]])

In [14]:
ex_arr.shape

(2, 3, 3)

In [15]:
ex_arr.ndim

3

In [16]:
ex_arr[0,:,:]

array([[1, 1, 4],
       [2, 2, 5],
       [3, 3, 6]])

In [17]:
# 4-dimension array example:
my_arr = np.array([[[[1,1,4],[2,2,5],[3,3,6]], [[1,1,4],[2,2,5],[3,3,6]]],
                   [[[1,1,4],[2,2,5],[3,3,6]], [[1,1,4],[2,2,5],[3,3,6]]]])
my_arr

array([[[[1, 1, 4],
         [2, 2, 5],
         [3, 3, 6]],

        [[1, 1, 4],
         [2, 2, 5],
         [3, 3, 6]]],


       [[[1, 1, 4],
         [2, 2, 5],
         [3, 3, 6]],

        [[1, 1, 4],
         [2, 2, 5],
         [3, 3, 6]]]])

In [41]:
len(my_arr)

2

In [18]:
my_arr.shape

(2, 2, 3, 3)

In [19]:
my_arr.ndim

4

In [20]:
my_arr[0,0,0,0]

1

In [21]:
# Choosing function like it works with lists
my_arr[:,:,:,:]

array([[[[1, 1, 4],
         [2, 2, 5],
         [3, 3, 6]],

        [[1, 1, 4],
         [2, 2, 5],
         [3, 3, 6]]],


       [[[1, 1, 4],
         [2, 2, 5],
         [3, 3, 6]],

        [[1, 1, 4],
         [2, 2, 5],
         [3, 3, 6]]]])

In [39]:
my_arr[0,1,:2,:1] # :2从第0个到第2个，但不包括第二个

array([[1],
       [2]])

In [23]:
# See below a list of lists:
lol = [ [1,2], [3,4], [5,6] ]
lol

[[1, 2], [3, 4], [5, 6]]

In [24]:
lol[0][1]

2

In [25]:
# bring this into numpy array
lol_np = np.array(lol)
lol_np

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
# what shape is our array
lol_np.shape

(3, 2)

> It's not exactly the same, but for now, we can think of this as a 3 row / 2 column Excel worksheet.  The `shape` attribute is something we are going to use quite a bit!



In [27]:
# how many dimensions within the array
lol_np.ndim

2

In [28]:
# how many elements total, or the size
lol_np.size

6

In [29]:
# remember, we can always get help
lol_np?

In [30]:
len(lol_np)

3

In [31]:
# Build 2,2,2,3
building = np.array([[[[2,2,4],[1,2,9]],[[2,1,2],[1,1,4]]],
                    [[[2,2,4],[1,2,9]],[[2,1,2],[1,1,4]]]])
building

array([[[[2, 2, 4],
         [1, 2, 9]],

        [[2, 1, 2],
         [1, 1, 4]]],


       [[[2, 2, 4],
         [1, 2, 9]],

        [[2, 1, 2],
         [1, 1, 4]]]])

In [40]:
len(building)

2

In [32]:
building.shape

(2, 2, 2, 3)

In [33]:
building.ndim

4

In [34]:
building.size

24

In [43]:
my_list = range(24)
array = np.array(my_list)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
arr_reshaped = array.reshape(2,2,2,3)
arr_reshaped

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [36]:
arr_reshaped[0,0,0,0]

0

## Quick exercise:

Generate an array of 10 integers sampled from a random distribution of [0,10).

confirm the length and shape of your array, and
calculate the mean, 
calculate the standard deviation.

In [54]:
x = np.random.randint(0,10,size=10)
x

array([0, 0, 6, 1, 8, 0, 5, 3, 5, 8])

In [56]:
x.shape

(10,)

In [57]:
x.ndim

1

In [59]:
x_new = x.reshape(2,5)
x_new

array([[0, 0, 6, 1, 8],
       [0, 5, 3, 5, 8]])



## Slicing

In [60]:
lol_np

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
lol_np.shape

(3, 2)

In [62]:
# lets slice the array - include everything
lol_np[:]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
# get just the first array
lol_np[0]

array([1, 2])

Multidimenstional arrays can be sliced using a comma separated set of tuples

In [66]:
# return just 5 
lol_np[2, 0]

5

lets look at a larger nd array

In [67]:
# generate a larger array
np.random.seed(765) # for reproducing example
x2 = np.random.randint(10, 20, size=(3, 4))
x2

array([[14, 11, 16, 13],
       [10, 16, 13, 12],
       [11, 10, 17, 14]])

In [68]:
# shape (rows/columns)
x2.shape

(3, 4)

In [69]:
# slicing to get all "rows" and first "column"
x2[:, 0]

array([14, 10, 11])

In [70]:
# 2 rows, 3 cols
x2[:2, :3]

array([[14, 11, 16],
       [10, 16, 13]])

In [71]:
# just get one row
x2[0]

array([14, 11, 16, 13])

In [72]:
# want to reverse?
x2[::-1,:]

array([[11, 10, 17, 14],
       [10, 16, 13, 12],
       [14, 11, 16, 13]])

In [73]:
# want to reverse? （起始位置：终止位置：步幅）
x2[::-1, ::-1]


array([[14, 17, 10, 11],
       [12, 13, 16, 10],
       [13, 16, 11, 14]])

In [74]:
x2

array([[14, 11, 16, 13],
       [10, 16, 13, 12],
       [11, 10, 17, 14]])

In [75]:
# we can also do math!
print(x2.mean())   #mean
print(x2.std())    #standard deviation
print(x2.max())    #max


13.083333333333334
2.289771944005681
17


## Quick exercise 

Update the value of x2 such that the element that was previously 17 becomes 71. You can locate the element manually.

In [76]:
x2

array([[14, 11, 16, 13],
       [10, 16, 13, 12],
       [11, 10, 17, 14]])

In [77]:
x2[2,2] = 71
x2

array([[14, 11, 16, 13],
       [10, 16, 13, 12],
       [11, 10, 71, 14]])

---


# Useful methods

In [88]:
# arange: like range, generate an array of numbers with bounds and spacing
x = np.arange(2,10,2)
x

array([2, 4, 6, 8])

In [89]:
# do some math and finding locations
print("the mean of the array is {}".format(str( x.mean() )))   # x.mean()
print("the largest value in the array is {}".format(str( x.max() )))   # x.max()
print("the index for the largest value in the array is {}".format(str( x.argmax() )))   # x.argmax()


the mean of the array is 5.0
the largest value in the array is 8
the index for the largest value in the array is 3


In [90]:
x

array([2, 4, 6, 8])

In [91]:
# we can generate an array of booleans for subsetting - this is very useful!
x > 5

array([False, False,  True,  True])

In [92]:
# we can also do complex logic: logical and
np.logical_and(x > 0, x <5)

array([ True,  True, False, False])

In [93]:
# logical or
np.logical_or(x > 5, x <7)

array([ True,  True,  True,  True])

---

## Discussion on logical_and/or

The concept of booleans across our arrays is a really important concept to understand.  This is the foundation for how we filter rows/columns in our data analysis in python (pandas, more specifically).  When slicing (i.e. filtering) our data, we keep the `True` elements.




In [94]:
# Let's see this in action
np.random.seed(765)
x = np.random.randint(0, 10, size=100)
print(x.shape)
x[:5]

(100,)


array([4, 1, 6, 3, 0])

In [95]:
x

array([4, 1, 6, 3, 0, 6, 3, 2, 1, 0, 7, 4, 4, 0, 1, 8, 3, 7, 8, 7, 7, 8,
       6, 8, 2, 8, 2, 6, 9, 1, 7, 4, 1, 9, 4, 8, 4, 5, 2, 5, 1, 1, 9, 0,
       5, 8, 0, 7, 4, 1, 1, 7, 2, 5, 1, 4, 1, 4, 7, 3, 5, 6, 4, 8, 3, 4,
       5, 0, 4, 0, 8, 0, 3, 2, 0, 8, 8, 5, 6, 2, 7, 8, 3, 5, 0, 6, 9, 2,
       1, 6, 2, 3, 3, 0, 0, 4, 4, 1, 3, 3])

In [96]:
x.ndim

1

In [98]:
# save a variable to store our test results
tests = (x >= 4)
tests[:5]

array([ True, False,  True, False, False])

In [99]:
# confirm that they are the same shape
x.shape == tests.shape

True

In [100]:
# finally, keep just those that meet our criteria
# WE ONLY KEEP THE TRUE
keep = x[tests]
keep.shape

(55,)

In [101]:
keep

array([4, 6, 6, 7, 4, 4, 8, 7, 8, 7, 7, 8, 6, 8, 8, 6, 9, 7, 4, 9, 4, 8,
       4, 5, 5, 9, 5, 8, 7, 4, 7, 5, 4, 4, 7, 5, 6, 4, 8, 4, 5, 4, 8, 8,
       8, 5, 6, 7, 8, 5, 6, 9, 6, 4, 4])

> To see a much larger list of what is possible for logical check in numpy, here are the docs:  https://numpy.org/doc/stable/reference/routines.logic.html

-----
-----

## Reshaping
Another method that comes very handy is reshaping arrays - the name is clear so there is not much to say about this than showing how it works:

In [102]:
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
my_array.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Mathematical Operations on Axis

Helpful resource:  https://www.sharpsightlabs.com/blog/numpy-axes-explained/

![axis](https://i.imgur.com/4aL45nA.png)

<br>

### What is really happening?

<br>

Axis 0 = we collapse/summarize *across* the rows

![axis0](https://vrzkj25a871bpq7t1ugcgmn9-wpengine.netdna-ssl.com/wp-content/uploads/2018/12/numpy-axes-np-sum-axis-0.png)

Axis 1 = we collapse/summarize *across* the columns


![axis1](https://vrzkj25a871bpq7t1ugcgmn9-wpengine.netdna-ssl.com/wp-content/uploads/2018/11/numpy-axes-np-sum-axis-1.png)


In [104]:
np.random.seed(765)
a = np.random.randint(0, 100, size=(3, 7))

In [105]:
a

array([[29, 90,  4, 46, 27, 81, 70],
       [92, 79, 60, 19,  0, 38, 18],
       [65, 16,  7, 42, 36, 64, 17]])

In [106]:
type(a)

numpy.ndarray

In [107]:
a.shape

(3, 7)

In [108]:
a.ndim

2

In [109]:
a.mean()

42.857142857142854

In [110]:
a.sum()

900

In [111]:
a.max()

92

In [112]:
a.min()

0

Now we will use the `sum` operation specifying the array axis (refer to images above)

We are summing across axis 0 (the first axis):

In [113]:
# add all the elements to the direction of axis-0 and leave as much elements as axis-1 has
axis0 = a.sum(axis=0)
axis0

array([186, 185,  71, 107,  63, 183, 105])

In [114]:
a.sum(axis=(0,1))

900

In [115]:
len(a.sum(axis=0))

7

What if we performed the sum across the other axis, axis 1? How many elements would it return?

In [116]:
axis1 = a.sum(axis=1)
axis1

array([347, 306, 247])

## Quick exercise:

Find the mean of the above array along various axes.

In [117]:
print(axis0.mean())
print(axis1.mean())

128.57142857142858
300.0


## Array operations
Now let's do some array operations 

In [120]:
# array ops
np.random.seed(765)
x = np.random.randint(0, 10, size=(10))
y = np.random.randint(20, 100, size=(10))
x

array([4, 1, 6, 3, 0, 6, 3, 2, 1, 0])

In [121]:
y

array([27, 62, 56, 84, 37, 28, 49, 75, 75, 26])

In [122]:
x - y

array([-23, -61, -50, -81, -37, -22, -46, -73, -74, -26])

In [123]:
x *y

array([108,  62, 336, 252,   0, 168, 147, 150,  75,   0])

In [124]:
np.random.seed(765)
x = np.random.randint(0, 10, size=(9))
y = np.random.randint(20, 100, size=(10))

In [125]:
x

array([4, 1, 6, 3, 0, 6, 3, 2, 1])

In [126]:
y

array([36, 27, 62, 56, 84, 37, 28, 49, 75, 75])

In [127]:
x - y

ValueError: ignored

In [128]:
print(x)

[4 1 6 3 0 6 3 2 1]


In [129]:
x

array([4, 1, 6, 3, 0, 6, 3, 2, 1])

In [130]:
# 返回列表中最大值的位置
x.argmax()

2

This is another very important function for arrays, and since we already saw how to build logical arrays using conditionals earlier, it will sound familiar:

In [131]:
?np.where

In [132]:
np.where(x >  3, True, False)

array([ True, False,  True, False, False,  True, False, False, False])


>np.where is great for feature engineering because we can evaluate our values and recode the columns however we want.

Below is an example of filtering:

In [133]:
np.where(x > 3, x, 3)

array([4, 3, 6, 3, 3, 6, 3, 3, 3])

# Summary

In this notebook, we learned 

- numpy generates arrays that are very powerful for analysis, and can be thought of enhanced lists

- numpy arrays must be of one type, else they will be converted to a singular type

- numpy arrays can be multidimensional

- numpy arrays can be sliced just like lists, with dimensional slicing occuring `[:, :]`

- we can perform mathematical operations using numpy